image: node:latest

variables:
  PUBLIC_URL: /foodapp

cache:
  paths:
  - frontend/node_modules

stages:
  - deploy

pages:
  stage: deploy

  script:
    - unset CI
    - cd frontend
    - npm install        # Install all dependencies
    - npm run build      # Build for prod
    - ls
    - mv public _public  # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public    # Move build files to public dir for Gitlab Pages

  artifacts:
    paths:
    - frontend/public
  publish:
    - frontend/public

  only:
    - main
